name: Daily Stripe Digest Workflow

on:
  schedule:
    # Run at 12:00 UTC daily
    - cron: "0 12 * * *"

jobs:
  ping-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the Stripe digest endpoint
        run: |
          curl -X POST 'https://your.serverless.function.endpoint'
        env:
          # If your endpoint requires an API key or other secret
          API_KEY: ${{ secrets.API_KEY }}
